index.js

I checked old commits and this is a leftover that is not used anymore

Remove unused itemType parameter

---

index.js
package.json

The main reasons for this are:
- Use a more widespread and maintained library than questor
- Fix an issue that seems to have been introduced with a recent update of questor, which introduces issues with CORS requests without a seemingly easy fix.

Use axios instead of questor

---

example/ufos/index.html
example/ufos/index.js
example/ufos/style.css

Hey @grncdr 
I have replaced the mapbox map with a google map as You suggested in (#28). Have a look if you like it... 
As far as I have seen you haven't been testing the ufo map functionality before. Since some of your tests were failing in my environment I didn't want to mess around with them.
Best,
Thomas

Replaced mapbox-map with Google map in ufo example

---

README.md

Also remove one last link to the old docs, and add a section on collections and pagination.

Add more search examples to docs. Fixes #34

---

index.es6.js
test/helper.js
test/integration/asset-test.js
test/integration/entry-test.js

Fixes #37
This PR correctly adds lodash to the library and removes it from the tests where it was made available globally.
ping @trodrigues @grncdr

Correctly require lodash

---

index.es6.js
package.json

This saves us roughly 200kb in the minified bundle

Remove lodash dependency

---

index.es6.js

Allows to define custom headers included in each request.

Allow defining custom headers

---

lib/entities/entry.js
test/integration/tests.js
test/unit/entities/entry-test.js

fix(links): Fix link resolution for links in same response

---

lib/sync.js
test/unit/sync-test.js

feat: Add stringifySafe and toPlainObject to sync responses

---

lib/contentful.js

Typo in hostname

---

.gitignore
lib/create-contentful-api.js
package.json
test/runner
test/unit/create-contentful-api-test.js

@stefanjudis could you take a look

feat(entities): add parseEntities method

---

lib/create-contentful-api.js
test/integration/tests.js

feat(contentful): Add sys property check for select

---

package.json

feat(sdk-core): update the sdk core dependency

---

CONTRIBUTING.md
README.md

This is my first fork + PR so please let me know if I am contributing the correct way. I just found those two typos while I was reading your documents and thought it would be nice to fix :)

Fixed some wording issues

---

README.md

Add a section about using es6 imports with the SDK

chore(README): Update README

---

lib/contentful.js
package.json

Enabel proxy, httpAgent and httpsAgent

---

.babelrc
.gitignore
package.json

fixes https://github.com/contentful/contentful.js/issues/164

fix(es6-modules): Add version to dist

---

.gitignore
test/integration/tests.js

This PR adds integration test for link resolution when using preview api.

test(integration): Add preview test

---

.babelrc
webpack.config.js

fix(ie11): transform Object.assign also in sdk-core

---

README.md

docs(README): fix unpkg url and add non-node environment hint

---

lib/contentful.js

docs(spec): add logHandler parameter to docs

---

index.d.ts

Added the ability to pass type parameter to `.getEntries` and `.getEntry`.

Improve type definitions

---

lib/contentful.js
lib/create-contentful-api.js
lib/entities/index.js
lib/entities/locale.js
package.json
test/integration/tests.js
test/unit/contentful-test.js
test/unit/create-contentful-api-test.js
test/unit/entities/locale-test.js
test/unit/mocks.js

This PR adds enables the SDK to use the environment endpoint.
CI might fail for now

Add Environment endpoint

---

lib/contentful.js
lib/create-contentful-api.js
test/unit/create-contentful-api-test.js

Thow an exception when trying to sync on an environment.
TODO:

feat(environment): Throw an Exception on sync

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Removing some stuff to make it less overwhelming.

docs(GitHub): reduce issue/pr template complexity

---

ADVANCED.md

Update the description of link resolution in ADVANCED.md to include differences between v7.0.0 (resolves links for `getEntry()`) and older versions (only collections endpoint resolves links).

docs(ADVANCED.md): Update link resolution description

---

lib/create-contentful-api.js

fix(getEntries): fix not found error

---

lib/paged-sync.js
package.json
test/integration/tests.js
test/unit/paged-sync-test.js

fix(Sync): add toPlainObject method to Entries and Assets

---

package.json

Fixes https://github.com/contentful/contentful.js/issues/290

fix(sdk-core): Bump sdk version

---

ADVANCED.md
README.md
lib/contentful.js
package.json

Allows the use of custom adapters with axios
Add info that custom adapters are supported which are then passed through to the sdk-core
Allow the use of the contentful sdk in a server side rendered angular application
Merge https://github.com/contentful/contentful-sdk-core/pull/67 to make this work
Not needed

Allow the use of custom adapters

---

index.d.ts

Few things missing from the Typescript definitions and some could be typed more strongly
- Add stronger typing to type field in Field interface
- Add validations to Field
- Add interface for validations
- Add support for Array type fields

feat(index.d.ts): improve typings

---

package.json
test/integration/tests.js

* Fix one integration test to work in the browser (since the shift to circle we aren't currently doing browser testing in CI)
* Update many dependencies to address vulnerabilities
Making this a `feat` so that sem-rel does another minor release once this is merged.

feat(dependencies): update dependencies

---

index.d.ts

Give appropriate type to `toPlainObject` method

Update type for toPlainObject method

---

lib/contentful.js
package.json

Add support for retry limit changes, add docs.

feat(timeout/retry): update documentation

---

lib/contentful.js
package.json
test/unit/contentful-test.js

Obscure authentication key in error logs.
For security reasons.

feat: obscure authentication token

---

lib/create-contentful-api.js

Throw error response data as expected.

Throw appropriate error response

---

lib/contentful.js
package.json
test/integration/tests.js

fix(error): consider errors without a response property

---

index.d.ts

fix(typings):add 'embedded-entry-inline' to RichTextNodeType

---

.gitignore
package-lock.json
package.json

To ensure the local setup (e.g. npm caching) does not interfere with the npm test scripts.

chore(tests): add package-lock.json

---

lib/common-types.ts
lib/contentful.ts
lib/create-contentful-api.ts
lib/create-global-options.ts
lib/paged-sync.ts
package-lock.json
package.json

feat(types): typed public api

---

lib/create-contentful-api.ts
package.json

With all the new TS features we use, we have to ensure a compatible version

feat(chore): ensure typescript version

---

MIGRATION.md
test/integration/tests.js

Use the right version the migration doc.

Change version in migration doc

---

README.md
package.json
tonic-example.js

remove outdated (also not working anymore) example for tonic platform

chore(examples): remove tonic example

---

lib/create-contentful-api.js
lib/entities/asset-key.js
lib/entities/index.js
lib/utils/validate-timestamp.js
test/integration/tests.js
test/unit/create-contentful-api-test.js
test/unit/entities/asset-key-test.js
test/unit/mocks.js
test/unit/utils/validate-timestamp-test.js

This feature is part of the Embargoed Asset release and provides entitled users
a convenient method to get the necessary asset keys for asset URL signing.
Further reading about Embargoed Assets and its application:
* Changelog entry:
https://www.contentful.com/developers/changelog/#embargoed-assets
* API documentation:
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/asset-keys/asset-key
* Guide for Embargoed Assets:
https://www.contentful.com/developers/docs/tutorials/general/embargoed-assets-getting-started/
* Help Center:
https://www.contentful.com/help/embargoed-assets-overview/
see Summary above
see Summary above

feat: add asset key generation

---

test/integration/tests.js
test/unit/create-contentful-api-test.js

feat(testing): add tests for param `removeUnresolved`

---

lib/contentful.js

Fix broken link in documentation. 
👉  https://contentful.github.io/contentful.js/contentful/8.3.7/contentful.html#.createClient

Update jsdoc for loghandler docs

---

index.d.ts

To solve https://github.com/contentful/contentful.js/issues/711

chore(typescript): add ts support for metadata on entities

---

index.d.ts

Includes missing tag types, fixes #806.

fix: add tag type definitions

---

.github/dependabot.yml
.github/workflows/dependabot-approve-and-request-merge.yml
README.md

feat(chore): setup dependabot

---

.github/workflows/dependabot-approve-and-request-merge.yml

🙄 I didn't specify the correct var name.

fix(dependabot): fix wrongly referenced github token var

---

MIGRATION.md

Update the version migration documentation with information on the latest contentful versions.

chore: update migration doc

---

catalog-info.yaml

Registed this library in our internal software catalog
Add backstage meta descriptor file
Internal maintenance.

chore: [] registed in internal backstage

---

test/integration/getEntry.test.ts

Same as this [PR](https://github.com/contentful/contentful.js/pull/1127) but for getEntries  
We cover 🏗
- default client
- withoutUnresolvableLinks + combinations
- withAllLocales + combinations
- withoutLinkResolution + combinations
```
getEntry via chained clients
default client
✓ client (164 ms)
client has withoutUnresolvableLinks modifier
✓ client.withoutUnresolvableLinks (108 ms)
○ skipped client.withoutUnresolvableLinks.withAllLocales
client has withAllLocales modifier
✓ client.withAllLocales (118 ms)
✓ client.withAllLocales.withoutLinkResolution (118 ms)
○ skipped client.withAllLocales.withoutUnresolvableLinks
client has withoutLinkResolution modifier
✓ client.withoutLinkResolution (106 ms)
✓ client.withoutLinkResolution.withAllLocales (126 ms)
```

expand getEntry integration tests for all chain modifiers

---

lib/contentful.ts

Fixes axios types. Ensured that the axios types (especially proxy) actually reflect the supported types linked in our docs https://github.com/axios/axios#request-config

fix(types): Fix axios types

---

lib/create-contentful-api.ts
lib/types/query/query.ts

Fix various type related issues according to beta QA test

fix(type): Various fixes related to types

---

lib/types/query/query.ts

Fix sys query params for getEntries and getAssets so that only actually functioning params will be suggested.

fix(types): Fix available sys query params[SDK-1993]

---

.github/dependabot.yml

fix(chore): enable dependabot for beta-v10

---

package-lock.json
package.json

Fix: move types from devDependencies to dependencies

fix: move types from dev dependencies to dependencies

---

README.md

Rendered: https://github.com/contentful/contentful.js/blob/66fc6ee5df56780ac5163e8fc2b98e46fca7f502/README.md

fix: mention v10 beta in readme

---

README.md

Current link to docs gives 404, this should fix it once released

fix: fix doc version in readme

---

index.d.ts

Type adjustment to Location in Entry Field
Fix: [#1274](https://github.com/contentful/contentful.js/issues/1274#issuecomment-1132527411)

fix: Location type

---

.contentful/vault-secrets.yaml

Add a vault-secrets file to enable using a secrets management solution

chore(secrets): add vault-secrets

---

.contentful/vault-secrets.yaml

chore(secrets): update vault-secrets

---

.circleci/config.yml
.github/workflows/dependabot-approve-and-request-merge.yml

Add/Modify CI/CD config to enable usage of secrets management

chore(secrets): add ci vault config

---

.circleci/config.yml
.contentful/vault-secrets.yaml

Add custom release template for secrets vault

fix(secrets): add custom release template

---

package-lock.json
package.json

Update to contentful-sdk-jsdoc major version 3.0.0 in order to support Github app token authentication.

fix(deps): update contentful-sdk-jsdoc to 3.0.0

---

package-lock.json
package.json

Fixed a missing dependency in the upstream dependency https://github.com/contentful/contentful-sdk-jsdoc

fix: docs build again [NONE]

---

package-lock.json
package.json

Due to missing requirements, axios major bump got merge and broke `master`

fix wrongly bumped axios dependency [NONE]

---

.github/dependabot.yml
package-lock.json
package.json

Update dependencies -and lock conflicting dependency.

chore: update and lock dependency versions [NONE]

---

.circleci/config.yml
.contentful/vault-secrets.yaml
.eslintrc.js
package.json
test/output-integration/node/package-lock.json

The missing piece to re-active releases on the beta branch

fix: release pipeline for beta branch

---

index.d.ts
package-lock.json
package.json

fix(typescript): update rich-text types

---

lib/types/link.ts
lib/types/resource-link.ts

Adding ResourceLink type. This was omitted previously by mistake.

DANTE-829 beta v10

---

package.json

Add semantic-release config for a new beta branch

chore: release config for beta-resource-links [DANTE-852]

---

README.md

Update documentation links to point to the versions from the branch.

docs: update links [DANTE-852]

---

package.json

The next version of the npm package should point to the same version as the beta version.

chore: updating the channel of the next version to beta-v10 [DANTE-863]

---

package.json

Fixing the next config for semantic-release

fix: fixing the next config for semantic-release

---

README.md
TYPESCRIPT.md

Updated docs for `allLocales` chain support for `getAsset` and `getAssets`.

feat: update docs for assets

---

package.json

reverting the last experimental semantic release configuration for the next channel

chore: fix next channel for semantic release config

---

package-lock.json
package.json

Revert commit 2ac543a9018ea4bd8e7ce86b1335fd4cd99d82ca which broke semantic release. Not sure how the PR got merged as it had errors.

fix: semantic release

---

TYPESCRIPT.md

fix Type in TYPESCRIPT.md
#1414

fix: invalid TypeScript doc

---

package-lock.json
package.json

Revert semantic release again.

fix: revert semantic release

---

lib/contentful.ts

Add comments for `createClient` method to document in TypeDoc.

chore: document createClient method

---

lib/types/collection.ts
lib/types/content-type.ts
lib/types/link.ts
lib/types/locale.ts
lib/types/metadata.ts
lib/types/resource-link.ts
lib/types/space.ts
lib/types/sys.ts
lib/types/tag.ts

I have added more type descriptions and documentation links for simple types.

feat: add documentation for simple type definitions

---

.github/dependabot.yml
package-lock.json
package.json

Revert semantic-release version and add rule to ignore versions above 19.

chore: pin semantic release version

---

package-lock.json
package.json

reverting semantic-release upgrade done by dependabot

chore: revert semantic-release version

---

ADVANCED.md
CONTRIBUTING.md
MIGRATION.md
README.md
TYPESCRIPT.md
test/integration/getEntries.test.ts
test/integration/getEntry.test.ts
test/integration/parseEntries.test.ts
test/unit/make-contentful-api-client-chained-modifier.test.ts

Proofread all `.md` files, including
* double checking if links work / exist
* fixing typos
* adjusting style for consistency
* updating outdated information (mostly in `CONTRIBUTING`)
Some style fixes come from auto-fixes in my editor 😄

Proofread documentation

---

package-lock.json
package.json

Revert axios bump causing type errors and blocking the release

fix: revert axios version bump

---

DOCS.md
MIGRATION.md
README.md
TYPESCRIPT.md

fix the Build status link and update the breaking change section of the MIGRATION.md to include the query type breaking change

fix: correct link for build status in all .md files

---

package-lock.json
package.json

reverting the axios version that was causing tests and pipeline to fail

fix: revert axios version

---

DOCS.md

Small update for the  TypeDoc main page.

chore: update typedoc docs main page

---

.github/dependabot.yml
package.json

cleaning up semantic release and dependabot config

chore: cleanup beta-v10 config

---

package-lock.json
package.json

- Bump contentful-resolve-response

chore: bump contentful-resolve-response

---

lib/types/query/select.ts

For select query we are missing types for metadata, thus causing errors for users trying to use it

feat: add metadata types for select query [ZEND-4163]

---

.circleci/config.yml

Updating our CI node env to be able to [upgrade semantic versioning](https://github.com/contentful/contentful.js/pull/2074)

Update Node versions in CircleCI config

---

.github/CODEOWNERS

Un-own package files for dependabot PRs to self approve and merge

chore: unown package files []

---

.contentful/vault-secrets.yaml

feat: github migration [EXT-5014]

---

package-lock.json
package.json
test/integration/getEntry.test.ts

upgrading csm & fixing tests broken by new behaviour in content api added in this [ticket](https://contentful.atlassian.net/browse/TOL-2035). change will be merged as breaking change

feat: upgrade csm []

---

ADVANCED.md

this PR adds a section in the Link resolution docs to explain how to resolve cross space links in contentful.js latest versions

chore: update doc with links resolution for cross space [DANTE-1620]

---

package.json

Deploy next

---

package-lock.json

BREAKING CHANGE: force release

---

package-lock.json
package.json

addresses https://github.com/contentful/contentful.js/issues/2303

fix: bump axios to address CVE

---

package-lock.json
package.json

addresses https://github.com/contentful/contentful.js/issues/2303

fix: bump axios to address CVE (v9)

---

DOCS.md
typedoc.json

Fixes small problem with typedoc deprecated `media` option`

chore: typedoc media fix

---

package-lock.json
package.json

We were using an older version of jsdoc (which had also been archived) This uses a fixed version that opts for jq over json to work in our CI environment

fix: bump docs version

---

MIGRATION.md

docs: v11 release docs

---

lib/types/asset.ts
lib/types/metadata.ts
lib/types/query/query.ts
lib/types/query/select.ts
test/integration/getEntries.test.ts
test/types/queries/asset-queries.test-d.ts

Add [Taxonomy concept](https://www.contentful.com/help/taxonomies-overview/) links to assets.

feat: [Groot-1484] Update types in the CDA library with taxonomy assets

---

package-lock.json
package.json
test/integration/utils.ts

Update content source maps package to latest version to include changes in PR: https://github.com/contentful/live-preview/pull/925

chore: update csm package [NONE]

---

package-lock.json
package.json

- swap out bundlesize for size-limit due to sec vuln

fix: swap out bundlesize for size-limit [EXT-5920]

---

package-lock.json
package.json

Bumps contentful-sdk-core to include this fix https://github.com/contentful/contentful-sdk-core/pull/526

fix: bump contentful-sdk-core to ensure httpsAgent isn't copied [EXT-5676]

---

package-lock.json
package.json

Updating Content Source Maps package to fix bug with undefined values causing issues in Next.js projects
Related PR: https://github.com/contentful/live-preview/pull/986

chore: update csm package [TOL-2540]

---

package-lock.json
package.json

Update Content Source Maps package to include latest bug fix:
https://github.com/contentful/live-preview/pull/1050

feat: update csm package []

---

package-lock.json
package.json

fix: Axios sec vuln [ZEND-6126]

---

lib/types/concept.ts
lib/types/link.ts

This PR introduces the `conceptSchemes` property to taxonomy concepts
This enables work to add this property in the API GET endpoints for concepts: 

feat: [GROOT-1872] add concept schemes to concepts
