contentful/contentful.js

lib/create-request-config.js
lib/entities/asset.js
lib/entities/content-type.js
lib/entities/entry.js
lib/mixins/link-getters.js
lib/mixins/to-plain-object.js
lib/sync.js

This cuts down the size of the minified and gzipped browser bundle by ~30% and helps me reduce the code size when using Contentful from npm in my webpack build.
I left the imports in test modules unchanged, because they won't be included in the final build.

Import individual lodash modules to make the bundle smaller

---

package.json

After our discussion in #59, I did a little digging and found what was wrong (I think?)
Unlike in your example app which is building for browsers, I am using webpack to build for a node target. Since there was no node option in the `package.json`, it would fall back to `index.js` and error trying to load `lib/contentful`.
This PR adds a node option to the package.json to support server-side builds such as this.

Support building for a server-side target #59

---

index.d.ts
package.json

This enables typescript users to use the library in strongly typed mode without writing their own type definition files.
The types are based on the library documentation. However, some properties of the content types were not documented, such as the contentType-link on the Sys interface, and has been added.

Add type definition file for typescript users

---

karma.base.conf.js
package.json
webpack.config.js

Since Axios is not compatible with UMD builds that cover `node`  and `browser` environment, we decided to split it up into to versions.
Fixes #131

fix(export): SDK is working in node again

---

index.d.ts

I want to be able to reference the `fields` array in my client-side code.

fixed "fields" member of ContentType interface

---

README.md

- updated to use const throughout the doc instead of var for consistency (const is used in newer sections of the doc and the rest of Contentful documentation)

docs(readme): update to use const instead of var

---

.babelrc
lib/contentful.js
lib/entities/asset.js
lib/entities/content-type.js
lib/entities/entry.js
lib/mixins/link-getters.js
lib/paged-sync.js
package.json
test/integration/tests.js
test/unit/create-contentful-api-test.js
test/unit/entities/content-type-test.js
test/unit/entities/entry-test.js
test/unit/mocks.js
test/unit/paged-sync-test.js
version.js
webpack.config.js

Based on https://github.com/contentful/contentful-sdk-core/pull/35
* Introduces object rest spread for a readable syntax of complex object assignments
* [mem](https://github.com/sindresorhus/mem) replaces `lodash.memoize`
* [clone](https://github.com/pvorb/clone) replaces `lodash.cloneDeep`
* [deep-get-set](https://github.com/acstll/deep-get-set) replaces `lodash.get`
* ES5 & ES6 replace the rest

refactor(dependencies): replace lodash with smaller dependencies

---

README.md
index.d.ts
lib/contentful.js
lib/mixins/link-getters.js
package.json

the sync API sends deleted entries without fields. This broke the link resolution. This small bug fix fixes the issue :)

Fix sync link resolution

---

README.md

The anchor link in the readme was broken. This PR fixes this. :)

fix(docs): Fix anchor link in Readme

---

lib/paged-sync.js
test/unit/create-contentful-api-test.js
test/unit/paged-sync-test.js

Also fixes error to be thrown properly since `error.data` was undefined.

fix(sync): remove type and content_type filter at second paged sync

---

package.json

@axe312ger introduced this https://github.com/contentful/contentful.js/commit/6326f90dea771e7c1e68dfa44e2311a35d5ec4ad
This change broke a bunch of my docker builds that depend on contentful.
This changes it back to simple HTTP interface for fetches packages.
Our docker builder's don't have git and I would prefer not having to add git just for a temporary fix.
The syntax is slightly more verbose but allows dependencies to still be managed by vanilla npm instead of requiring git to be installed and configured.

Remove git dependency for package axios.

---

package.json

We need to rebuild the SDK with the new core SDK since we distribute the dist on npm

fix: fix user agent detection

---

lib/contentful.js
package.json
test/unit/contentful-test.js

The scoped package was added in https://github.com/contentful/contentful.js/pull/202.  However, the code was not updated to use the scoped package module.
This was accidentally working (but using the normal axios package) because a devDependecy installs axios to node_modules:
```
$ npm ls axios
contentful@0.0.0-determined-by-semantic-release /home/spainhower/repos/contentful.js
└─┬ bundlesize@0.12.2
├── axios@0.16.2 
└─┬ github-build@1.2.0
└── axios@0.15.3 
```
Closes #201

fix(axios): Use scoped import in code/tests

---

README.md

I replaced the unpkg link with a [jsDelivr CDN link](https://www.jsdelivr.com/package/npm/contentful) in your readme. jsDelivr works similarly to unpkg but was built specifically for production usage and offers a large network and better reliability.

Replace unpkg with jsDelivr

---

README.md
lib/create-contentful-api.js
lib/paged-sync.js
package.json
test/unit/paged-sync-test.js

Huge spaces might be problematic with the current sync implementation since it stores all results in the memory till it is done syncing. This allows the SDK user to disable this automatic pagination.
Fixes #220

feat(sync): sync can now be used without pagination

---

package.json

fix(user-agent): don't detect node when babel-polyfill is used

---

index.d.ts

This adds missing `CreateClientParams` TypeScript type definitions and  fixes #239.

Add missing CreateClientParams type definitions

---

package.json

With the release of Webpack 4, there's a [`resolve.mainFields` configuration](https://webpack.js.org/configuration/resolve/#resolve-mainfields), which defines which `package.json` fields are checked in which order to determine the entry point of a package import.
Without a `target`(or `target` being `web` / `webworker`) the order is the following:
```js
mainFields: ["browser", "module", "main"]
```
Angular 6 for example seems to have not altered such main fields or targets, causing #243.
I used the example project Khaled created here: https://github.com/contentful/contentful.js/issues/243#issuecomment-390141336
I could remove the manual `paths` mapping, and the type was correctly inferred again.

Add browser entry point to package.json

---

README.md

Reverts contentful/contentful.js#244
After #247 landed, these instructions are no longer needed.

Revert "docs: Add instruction about Angular 6"

---

package.json

Had to rerelease v4 of the sdk. This ensures that v6 is installed on fresh projects. Should have added a tag to the release. Sorry.

fix(version): make sure latest v6 is on latest

---

README.md

This pull request is to add documentation on how to configure which environment the user wants to communicate with. By default, `master` is set the environment.
Added a row in the `Configuration` table to show that `environment` can be set, and that the default environment is `master`.
I have API keys that talk to specific environments, but I didn't know how to set which environment within my client. I had to go into the source code to see if this was possible. Since it is, I just wanted to add documentation to let others know that this is easily possible.

docs: add environment setup to `createClient` configuration

---

package.json

We can safely remove the browser field now thus fixing the webpack tree shaking. See relevant issue:
https://github.com/contentful/contentful.js/issues/260

Fix: Remove browser field as contentful-sdk-core has been fixed now

---

index.d.ts

Adding the missing method `getLocales()` to the Contentful client interface
Added:
- `getLocales()` method (documented and implemented https://contentful.github.io/contentful.js/contentful/7.0.0/ContentfulClientAPI.html#.getLocales) but not declared in the `index.d.ts`
- `Locales` interface
If the Contentful library will be used with a Typescript compiler it will throw errors because the declaration of the type is missing from the `index.d.ts` file.

Add getLocales and Locales interface to index.d.ts

---

index.d.ts

TS linter complains when you try to call stringifySafe without args as suggested here:
https://www.contentful.com/developers/docs/javascript/tutorials/using-the-sync-api-with-js/

Make arguments Optional for Stringify safe method

---

README.md

This PR fixes docs homepage which had problem with github-relative links to files such as ADVANCED.md etc. I've added absolute links to the README file, so now they should work properly regardless of environment. 
I've changed links to files ADVANCED.md, MIGRATION.md and CONTRIBUTING.md in README file. 
PR fixes this issue:
https://github.com/contentful/contentful.js/issues/259

fix(docs) Add proper (absolute) links to README.md file

---

index.d.ts

The `items` attribute in a Content Type is not an array, it's an object, and it gives a summary of the types that are IN the array. This PR fixes the type. Example response straight from the API for proof:
```json
{
"id": "logos",
"name": "Logos",
"type": "Array",
"localized": false,
"required": true,
"validations": [{ "size": { "min": 5, "max": 15 } }],
"disabled": false,
"omitted": false,
"items": {
"type": "Link",
"validations": [{ "linkContentType": ["logo"] }],
"linkType": "Entry"
}
}
```

fix(types): Correct the type for Field['items']

---

index.d.ts

This includes a fix for https://github.com/contentful/contentful.js/issues/293
Added missing methods to types
Typescript error is thrown whenever `.update` is used

fix(type): Add type definitions

---

index.d.ts

🤔Looks like the type is wrong.
[![Image from Gyazo](https://i.gyazo.com/ccdb8f7d68f5f9b9ae25871bc420fe9b.png)](https://gyazo.com/ccdb8f7d68f5f9b9ae25871bc420fe9b)
Its `content` is really array but type is object.
I changed it into array.

fix: fix EntryFields.RichText types

---

lib/mixins/stringify-safe.js
package.json
test/unit/entities/entry-test.js
test/unit/mixins/stringify-safe-test.js

Json-stringify-safe https://www.npmjs.com/package/json-stringify-safe is slow and unreliable, or perhaps broken. This PR uses a decycling algorithm by Douglas Crockford https://github.com/douglascrockford/JSON-js/blob/master/cycle.js.

fix(stringify): Replace json-stringify-safe package

---

lib/contentful.js

This PR addresses undefined error thrown when obscuring access token.
-   [x] Feature with pending implementation

Address missing values in the error response

---

lib/create-contentful-api.js
test/integration/tests.js

Invoking `getEntry` without passing an ID should fail.
-   [x] Feature with pending implementation

fix: throw an error when entry id is undefined

---

lib/paged-sync.js
test/unit/paged-sync-test.js

Handles deleting the `limit` from subsequent sync calls if present on the initial call
A change has been introduced to the Sync API endpoint that allows a limit to be provided on the initial call that must not be provided on subsequent calls. This PR deletes that query parameter from subsequent calls if present.

feat: Allow limit in sync API

---

index.d.ts

Changes the `Sys` definition in types to include `revision` and `space` fields.
Changes the `Sys` definition in types to include `revision` and `space` fields. They're included optionally -- `revision` is actually optional, since it's `undefined` for unpublished content. I left `space` as optional in order to avoid a breaking change. The type for `space` is defined similarly to the existing definition for `contentType`.
`contentType` should also probably be optional (since it's not set on the `sys` field for content types), but I wasn't entirely sure on that.
Fixes #351

fix(types) add revision and space to Sys interface

---

index.d.ts

It turned out changes made earlier to `SYS.contentType` are too strict.
Even though, there are rare cases where `contentType` can be missing, we will keep it required for now.
This problem has been reported in context of another [PR](https://github.com/contentful/contentful.js/pull/368) 
**Update:**
We also identified `space` as an optional field and added the changes to this PR.

fix(chore): SYS type declaration

---

package.json

Bump [contentful-sdk-core version](https://github.com/contentful/contentful-sdk-core/releases/tag/v6.4.5)

build(deps): bump contentful-sdk-core from 6.4.0 to 6.4.5

---

package.json

This fixes a performance issue our customers have on really big spaces. The fix itself was implemented already in contentful-resolve-response
Details:
* https://github.com/contentful/contentful-resolve-response/pull/35
* https://github.com/contentful/contentful-resolve-response/issues/30
* Will solve: https://github.com/gatsbyjs/gatsby/issues/25464
Thanks a bunch :)

fix(perf): improve performance of resolving huge data sets

---

lib/paged-sync.js
test/unit/paged-sync-test.js

We were not handling the case where the request to the sync api returned no items, which caused errors in user applications, failing because items was undefined. This PR gracefully handles this case.
Fixes #432

fix(paged-sync): return empty array if sync api returns nothing

---

.babelrc.js
karma.base.conf.js
lib/entities/asset.js
lib/entities/content-type.js
lib/entities/entry.js
lib/entities/locale.js
package-lock.json
package.json
test/unit/entities/content-type-test.js
test/unit/entities/entry-test.js
test/unit/mocks.js
test/unit/paged-sync-test.js
webpack.config.js

Fixes https://github.com/contentful/contentful.js/issues/408 by completely removing lodash.
The `cloneDeep` functionality was replaced with `fast-copy`.
This might also already have a slight positive impact on https://github.com/contentful/contentful.js/issues/428
Bundle sizes:
Before:
PASS  ./dist/contentful.browser.js: 44.76KB < maxSize 50KB (gzip)
PASS  ./dist/contentful.browser.min.js: 15.84KB < maxSize 16KB (gzip)
PASS  ./dist/contentful.legacy.js: 44.76KB < maxSize 64KB (gzip)
PASS  ./dist/contentful.legacy.min.js: 15.84KB < maxSize 25KB (gzip)
PASS  ./dist/contentful.node.js: 57.94KB < maxSize 60KB (gzip)
PASS  ./dist/contentful.node.min.js: 22.54KB < maxSize 23KB (gzip)
After:
PASS  ./dist/contentful.browser.js: 38.74KB < maxSize 50KB (gzip)
PASS  ./dist/contentful.browser.min.js: …

feat: remove lodash

---

lib/create-contentful-api.js
lib/utils/normalize-select.js
test/unit/utils/normalize-select-test.js

Fixes https://github.com/contentful/contentful.js/issues/296 and sort of fixes https://github.com/contentful/contentful.js/issues/430
Might be the cause for https://github.com/contentful/contentful.js/issues/444 too.
Basically the SDK always needs `sys.id` and `sys.type` to perform link resolution.  
Other `sys` fields are optional from what I can tell.
Previously the SDK would simply check if the string `sys` appears in the `select` section of the query and continue with that if it did, and add `sys` if it did not.
This led to the problem where selecting for example just `sys.id` would fail link resolution because `sys.type` was not included. It also led to the problem where not selecting `sys` as an optimization would always force the entire sys object back into the query. 
Now we …

fix: ensure minimum select

---

lib/create-contentful-api.js
lib/paged-sync.js
package.json
test/e2e/index.js
test/integration/tests.js
test/runner
test/runner-browser.js
test/unit/create-contentful-api-test.js
test/unit/paged-sync-test.js

BREAKING CHANGE: Some functions that used to throw synchronously for things like bad parameters now reject the promise.
In many cases users may not have to do anything assuming the calls already happened within a promise chain, but in rare cases this may need some refactoring of error handling cases.

refactor: replace promises with async/await

---

.babelrc.js
MIGRATION.md
package.json

We bumped the minimum version of Node to v12
This should have happened in the last release already, but was forgotten about.
While v10 is still on  Maintenance LTS, it will be EOL by the end of Q1 2021.
Thus we're jumping directly to v12 - however most likely the library will work perfectly fine also with v10 since currently we are not using any features unique to v12.
Fixes the problem mentioned in https://github.com/contentful/contentful.js/pull/496#issuecomment-738065819
That is, currently any node project would need to use regenerator so we can stay compatible with an ancient node version.

fix: ensure the node bundle uses native async/await

---

lib/create-contentful-api.js
lib/utils/normalize-select.js
test/unit/utils/normalize-select-test.js

Previously we did not officially, support arrays for the select operator, though it would sometimes work nonetheless.
This change ensures that we do support arrays and that they too are normalized properly.
Additionally, we stop mutating the query object in the select normalization and always return a copy.
Fixes https://github.com/contentful/contentful.js/issues/503

feat: allow arrays for select

---

lib/create-contentful-api.ts
lib/paged-sync.ts
package-lock.json
package.json
test/unit/create-contentful-api.test.js
test/unit/paged-sync.test.ts

Migrate sync api
Migrate all related tests. 
Use `http.cloneWithParams`  to eliminate global state switching of `http.defaults.baseURL`

feat(api): migrate sync

---

lib/create-contentful-api.ts
lib/index.ts
lib/query.ts
package-lock.json
package.json
test/unit/mocks.ts
test/unit/types.test.ts
tsconfig.json

Use barrel file (`index.ts`) as the main entry point.
- Introduce strict typescript config.
- fix entry point references in `package.json`
We currently enforce `typescript4.1.x` (with [template literals support](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types)) by deleting `node_modules/tsdx/node_modules`
In my opinion, we have to leave out the `FieldsQueries` type for now, and build with `typescript@3.x`

fix(chore): bundle export

---

jsdoc.json
package.json

Make use of [better-docs](https://github.com/SoftwareBrothers/better-docs/) to generate our documentation 
Once we are done with the TS migration, we should document `common-types`.
E.g
```
/**
* AssetDetails'
* @category Types
* @alias AssetDetails'
* @typedef {object} AssetDetails'
* @property {number} size '
* @property {object} image'
* @property {number}  image.width'
* @property {string} image.height '
*/
export interface AssetDetails {
size: number
image?: {
width: number
height: number
}
}
```

feat(docs): create documentation with better-docs

---

lib/common-types.ts
lib/create-contentful-api.ts
package-lock.json
package.json

The locally defined types for rich text content are inaccurate. 
Instead, we use a dedicated types package for `rich-text- types`.

Use rich text types package

---

package.json

According to my npm audit result I could figure out, that an old version of axios is used, which allows an Server-Side Request Forgery.
This vulnerability was fixed in 0.21.1.
I updated the axios dependency to 0.21.1 to fix the security vulnerability.
It's a Server-Side Request Forgery vulnerability which was found by `npm audit` and classified as "high".

Updated axios dependency

---

.babelrc.js
package-lock.json
package.json
test/integration/tests.js
test/runner-browser.js
webpack.config.js

Fixes the bundling of this library.
When doing a webpack build with a simple setup like [this](https://github.com/rustyy/contentful-issue-545), you get a `ReferenceError`:
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```
I managed to reproduce the problem. As a quick fix for now, I suggest you replace:
```javascript
import {createClient} from 'contentful';
// and same for
import {createClient} from 'contentful/dist/contentful.legacy';
```
with:
```javascript
import {createClient} from 'contentful/dist/contentful.browser';
```
> the browser bundle has native async support
**The reason why this is happening is that some bundles expect the regeneratorRuntime, but we don't bundle them.**
- `contentful` points to `dist/es-modules/contentful.js` (expects regeneratorRuntime)
- …

fix(chore): bundle building

---

README.md

Add some missing options by `createClient` in the Readme

chore(readme): add missing options for createClient

---

README.md

- Add a line height of 1.1 to the readme title - see before and after screenshots
**Before:**
Screen capture example -> https://gyazo.com/8fdeeebecd655860c7b371b3b5e804f1
**After:**
Screen Capture Example -> https://gyazo.com/7698329405bb6fadb8ff6406d0785fdb
Adding a line height style to the readme title
For screens smaller than XL the text wraps over self

add line height styling to README title

---

test/integration/tests.js

We added a new content model to test entry with multiple [references](https://github.com/contentful/contentful-management.js/pull/829), this causes tests to fail in other PRs

fix: add new content model to tests

---

lib/create-contentful-api.js
lib/entities/index.js
lib/entities/tag.js
test/integration/tests.js
test/unit/create-contentful-api-test.js
test/unit/entities/tag-test.js
test/unit/mocks.js

feat: add tags support

---

.github/dependabot.yml

Remove registry references as we don't rely on private dependencies and the reference broke our setup.

fix(dependabot): do not refer to npm registry in config

---

lib/contentful.js
lib/create-contentful-api.js
package-lock.json
package.json
test/unit/create-contentful-api-test.js

BREAKING CHANGE: stop sending Axios error object
Introduce a new error handling function and parse Axios' error object.
Use the error handling function from the contentful-sdk-core library that handles and returns better-parsed errors.
We want to obscure tokens returned in the error response object. With this change, we're implementing a better way to obfuscate and parse the error response we get from Axios.

feat(errors): improve error data thrown

---

index.d.ts
package-lock.json

Raw CDA responses include an `environment` field in each entity's `sys` field, which is not currently reflected in the `Sys` typedef.  This PR introduces `environment` as an optional `SpaceLink` in the `Sys` interface, which should better support typing CDA response entities.

fix(types): add optional environment SpaceLink to Sys interface

---

lib/create-contentful-api.js

Fix the example code for getEntries to prevent syntax error
Previous example code for the getEntries API method led to syntax error when copied 1:1. 
Fixed the example code.

docs(api-methods): fix example of getEntries

---

package.json

Change main entry point to the node (CJS) build. 
The browser build can still be accessed via the "browser" field and will be respected by bundlers.

fix(package): Change main entry point to node build

---

README.md
lib/create-contentful-api.ts
lib/types/entry.ts
lib/types/locale.ts
test/integration/tests.test.ts
test/types/entry-d.ts
test/unit/create-contentful-api.test.ts

Update name of chained client modifiers
- update names of client modifiers. `localized` to `withAllLocales` and `unresolved` to `withoutLinkResolution`
- update related type names
- fix/improve tests
- remove locale function param in calls to `withAllLocales` client and query `locale='*'` as default

Update name of client chains & fix some tests

---

lib/create-contentful-api.ts
lib/utils/validate-timestamp.ts
lib/utils/validation-error.ts
test/integration/getEntries.test.ts
test/integration/tests.test.ts
test/unit/make-contentful-api-client-chained-modifier.test.ts

- **Default** **client** shows a warning if `locale: '*'` param is provided, pointing to the new dedicated client 
- **Localized** **client** throws an error if `locale` property is provided

Restrict locale param from clients

---

lib/create-contentful-api.ts
test/unit/make-contentful-api-client-chained-modifier.test.ts

- add tests for resolveLinks warnings and errors ✅ 
- implement according to test structure ✅ 
- Double check potential "false positive" warnings when parameter is set not by the user but programmatically. ✅ 
Should be merged into `next-typescript` after [feat/localized-client-restrict-locale-param](https://github.com/contentful/contentful.js/tree/feat/localized-client-restrict-locale-param).

Restrict usage of unresolved param

---

test/unit/make-contentful-api-client-chained-modifier.test.ts

The old setup for some reasons didn't clean up the mock correctly between different test runs.
To reproduce, make one test fail, e.g. by changing the expected warning, which will trigger a failure not only for that test but also for the one running afterwards.

chore(tests): globally clear mock in chained mod tests

---

test/integration/getEntries.test.ts
test/integration/tests.test.ts

We changed the structure of the **getEnttries** tests, instead of adding all the tests in the matrix, we group them by client and its possible combination with other clients
We cover 🏗
- default client
- withoutUnresolvableLinks + combinations
- withAllLocales + combinations
- withoutLinkResolution + combinations
```
getEntries via chained clients
default client
✓ client (180 ms)
client has withoutUnresolvableLinks modifier
✓ client.withoutUnresolvableLinks (113 ms)
○ skipped client.withoutUnresolvableLinks.withAllLocales
client has withAllLocales modifier
✓ client.withAllLocales (112 ms)
✓ client.withAllLocales.withoutLinkResolution (107 ms)
○ skipped client.withAllLocales.withoutUnresolvableLinks
client has withoutLinkResolution modifier
✓ client.withoutLinkResolution (110 ms)
✓ …
```

Expand get entries integration tests

---

lib/contentful.ts
lib/create-contentful-api.ts
test/integration/tests.test.ts
test/unit/make-contentful-api-client-chained-modifier.test.ts

Remove * as an option for the locale query param for getEntries and getEntry. The query param `locale='*'` has been deprecated in favor of the client chain `withAllLocales`.

feat(params): Remove asterisk as option for locale in client query param [SDK-1979]

---

lib/types/query/equality.ts
lib/types/query/existence.ts
lib/types/query/location.ts
lib/types/query/range.ts
lib/types/query/search.ts
lib/types/query/subset.ts

Adds optional (field) keys to known field types.
If a field is optional, we also add generate a mapped type for it.

feat(types): suggest optional keys

---

lib/create-contentful-api.ts
test/integration/tests.test.ts

Adds the ability to use full-text search for content types collection endpoint.

feat(content-types): add query params

---

TYPESCRIPT.md
lib/types/query/search.ts
test/types/query-integer.test-d.ts
test/types/query.test-d.ts

Removed TS suggestion for `match` operator on fields with Integer type, as those are not supported.

fix: don't allow match operator for number fields

---

package.json

Rename prerelease channel to `beta-v10`

fix: rename prerelease channel

---

package.json

Removing the --dry-run flag from semantic-release

fix: remove --dry-run from semantic-release

---

README.md

Temporarily hardcoding v9 into docs link, so that it doesn't automatically point to v10-beta

fix(readme): point to docs for v9

---

test/integration/tests.js

- Explain exposure of access tokens
- I decided against additionally extracting the values + space ids into their own constants, as they are only used once here in the corresponding already descriptive objects, and for any future change, all object values would have to be replaced together.

chore(test): add comment

---

package-lock.json
package.json

Update internal dependencies. Similar to https://github.com/contentful/contentful.js/pull/1216 we needed to make sure that all our dependencies use fast-copy 2.1.3 to avoid problems with the build.
See: https://github.com/planttheidea/fast-copy/pull/65

fix(dep): Update dependencies

---

package.json
print-beta-v10-message.js

Print note about new beta version after installation
```sh
---------------------------------------------------------------------------------------------
contentful.js - the contentful delivery API (library)
🚨 We have just released contentful.js v10 in Beta with enhanced ✨ TypeScript ✨ support! 🚨
You can check it out on npm under the beta-v10 tag (go to the "Versions" tab to find it).
The migration guide and updated v10 README and can be found on the beta-v10 branch.
README: https://github.com/contentful/contentful.js/blob/beta-v10/README.md
MIGRATION GUIDE: https://github.com/contentful/contentful.js/blob/beta-v10/MIGRATION.md
BETA BRANCH: https://github.com/contentful/contentful.js/tree/beta-v10
--------------------------------------------------------------------------------------------- …
```

fix: add note about new beta version

---

lib/types/query/index.ts

See https://github.com/contentful/contentful.js/issues/1272 for context.
@marcolink

Use type only exports to support isolatedModules

---

lib/types/entry.ts
test/types/query-location.test-d.ts

Fix location type from `string` to `number`
Related to: [#1274](https://github.com/contentful/contentful.js/issues/1274)

fix: location type (string -> number)

---

lib/create-contentful-api.js
lib/entities/entry.js
test/integration/tests.js
test/unit/create-contentful-api-test.js
test/unit/entities/entry-test.js
test/unit/mocks.js

Write tests for xspace support and update jsdocs:
- Unit tests for ResourceLink
- Integrations tests for ResourceLink
- Add ResourceLink to jsdocs
You can find the content type for integration tests [here](https://app.contentful.com/spaces/ezs1swce23xe/content_types/catalog/fields).
You can find the entry for  integration tests [here](https://app.contentful.com/spaces/ezs1swce23xe/entries/6yfSzwXo99q8BKzkE5AIKo).

feat: xspace support

---

lib/types/content-type.ts
test/integration/tests.test.ts
test/unit/make-contentful-api-client-parseentries.test.ts
test/unit/make-contentful-api-client.test.ts
test/unit/mocks.ts

Write tests for xspace support and update jsdocs:
- Unit tests for ResourceLink
- Integrations tests for ResourceLink
- Add types
You can find the content type for integration tests [here](https://app.contentful.com/spaces/ezs1swce23xe/content_types/catalog/fields).
You can find the entry for  integration tests [here](https://app.contentful.com/spaces/ezs1swce23xe/entries/6yfSzwXo99q8BKzkE5AIKo).

xspace support beta v10

---

lib/create-contentful-api.ts
lib/types/entry.ts
lib/types/query/query.ts

Hey. I'm using your library in version `10.0.0-beta-v10.8` in a Next.js based project. Currently I'm getting the following TypeScript errors with TypeScript v4.8.3. This merge request fixes the errors.
Edit: I think TypeScript has become more strict in current versions concerning generics. I've tested it with different TypeScript versions. 4.5, 4.6 and 4.7 work fine, no type errors. Since 4.8 you get below errors.
```shell
yarn run v1.22.19
$ nextjs-project/node_modules/.bin/tsc
node_modules/contentful/lib/types/entry.ts:75:57 - error TS2344: Type 'LinkedEntryFields' does not satisfy the constraint 'FieldsType'.
75       ? EntryWithLinkResolutionAndWithUnresolvableLinks<LinkedEntryFields> | EntryLink
~~~~~~~~~~~~~~~~~
node_modules/contentful/lib/types/entry.ts:74:83
74     [FieldName in …
```

Fix TypeScript generic constraints

---

.github/dependabot.yml
package-lock.json
package.json

Lock `fast-copy` to version `2.x`. Version 3 caused errors with default exports.

fix: broken fast-copy dependency [NONE]

---

package-lock.json
package.json

Last dependency update to ensure all upstream deps lock `fast-copy`

fix: broken fast-copy dependency 2

---

.babelrc.js

resolves https://github.com/contentful/contentful.js/issues/1601
---
It seems counterintuitive, but;
```
@babel/preset-env: The 'modules' option must be one of 
- 'false' to indicate no module processing
- a specific module type: 'commonjs', 'amd', 'umd', 'systemjs' - 'auto' (default) which will automatically select 'false' if the current
process is known to support ES module syntax, or "commonjs" otherwise
```
Meaning by setting it to false, it won't try to process modules into CJS etc.
The contentful-sdk-core package does this as well
https://github.com/contentful/contentful-sdk-core/blob/c7841fe403e1a2f62a45b9777857a4180676afdd/rollup.config.js#L21-L26

fix: compile ESM modules

---

package-lock.json
package.json

Bump contentful-sdk-core to 7.0.5 in order to include [fix for setting custom headers](https://github.com/contentful/contentful-sdk-core/commit/685a29398d108cc0f1dd5c0301f5ed9f19b9498e).

fix(): bump contentful-sdk-core 

---

index.d.ts

Adding allowedFields to content type Field interface. This was omitted previously by mistake. It is available in beta-v10: https://github.com/contentful/contentful.js/blob/beta-v10/lib/types/content-type.ts#L25.

feat: add allowed resources to Field

---

lib/types/query/index.ts

Expose the type `FieldType` on root-level. This type is the base type for all field definitions, and is likely to be used in client code.

fix: expose FieldType

---

package.json

As the generated modules are currently not satisfying the `es6` check anymore anyway (due to some overlooked js files in the `es-modules` root folder), we bump to `es2017` so what we are consistent among all artifact checks (browser and node are already only satisfying `es2017`). 
We also make sure that the js files in the root folder are included in the checks from now on (if there is a better blob pattern for this, please let me know).
This is where the checks were introduced: https://github.com/contentful/contentful.js/pull/390.

chore(es-check): check generated modules for es2017 instead of es6

---

webpack.config.js

In order to avoid the usage of the `Function` operator in our browser bundle, as this runs into CSP issues (see https://github.com/webpack/webpack/issues/5627 and https://github.com/webpack/webpack/issues/6461) we adjust the webpack config: We set the `global` variable to `false` and by doing this avoid that webpack runs a check which makes use of the function constructor (https://github.com/webpack/webpack/blob/fb8afe71385734cfd65f47949117306a91f20753/buildin/global.js#L10).

fix(webpack): adjust bundler to avoid using function constructor

---

package.json

Cherry-picked commit from master to allow release of resource links beta.

fix(): release config for beta-resource-links [DANTE-852]

---

lib/create-contentful-api.ts
lib/types/asset.ts
test/integration/getAsset.test.ts
test/integration/getAssets.test.ts
test/types/asset-d.ts
test/types/client/createClient.test-d.ts
test/types/client/getAssets.test-d.ts

Similar to `getEntries` and `getEntry`, we want to support client chaining of `client.withAllLocales` for `getAssets` and `getAsset`. This also includes types and type tests.

Add support for withAllLocales client chain for getAsset/getAssets

---

lib/create-contentful-api.ts
lib/make-client.ts
lib/types/entry.ts
lib/utils/client-helpers.ts
test/types/asset-d.ts
test/types/chain-options.test-d.ts

Use new chain option types introduced in https://github.com/contentful/contentful.js/pull/1695 consistently and follow conventions for modifier names as suggested in  https://github.com/contentful/contentful.js/pull/1695#discussion_r1109549704.
* Replace remaining uses of old chain option types of format `ChainOptionWithAllLocalesAndWithoutLinkResolution`
* Move configured entry types to proper type file
* Update modifier enum names to match convention for constant names and match actual options / chain modifiers more closely.
* Make configured entry type more strict.

chore: use simplified chain option types consistently

---

lib/create-contentful-api.ts
lib/types/entry.ts
test/types/entry-d.ts
test/types/resolved-field.test-d.ts

Fix two issues with `Entry…` types and introduce a new configurable entry type to avoid similar issues in the future because we don’t have to write new definitions for every combination of modifiers.
* Fix: `EntryWithoutLinkResolution` no longer allows resolved entries for reference fields.
* Fix: `EntryWithAllLocalesAndWithLinkResolutionAndWithUnresolvableLinks` now allows unresolvable links.
* Introduce `NewEntry` type that takes `ChainModifiers` to get the specific type.
* Introduce `GenericEntry` alias for `Entry` type and deprecate `Entry` type
* Introduce `GenericEntryCollection` alias for `EntryCollection` type and deprecate `EntryCollection` type.
The following changes will be done in a separate PR to reduce conflicts.
* Renaming the generic `Entry` type `GenericEntry`.
* Renaming …

fix: correct entry types and add chain modifiers

---

lib/create-contentful-api.ts
lib/make-client.ts
lib/types/asset.ts
lib/types/entry.ts
lib/types/sync.ts
lib/utils/client-helpers.ts
test/types/asset-d.ts
test/types/chain-options.test-d.ts
test/types/client/getAssets.test-d.ts
test/types/client/getEntries.test-d.ts
test/types/entry-d.ts
test/types/mocks.ts
test/unit/mocks.ts

The newly introduced `NewEntry` type was already used for all cases where we know exactly what the entry shape is but we kept the old `Entry` type for some cases where a generic entry type was needed. This PR expands the `NewEntry` type to support generic cases and replace all existing entry types, namely `Entry`, `EntryWith…`, `GenericEntry`, `ConfiguredEntry`, `EntryCollection`, `EntryCollectionWith…`, `ConfiguredEntryCollection`.
* Replace existing entry types with `NewEntry`
* Replace `EntryCollectionWith…` types with a new `EntryCollection<NewEntry<…>>` type format
* Rename `NewEntry` to `Entry`
* Introduce new `Asset` type following the same structure as the new entry
* Replace existing asset types `AssetWithAllLocales`, `GenericAsset`, `ConfiguredAsset`, …

chore: replace old entry types

---

lib/types/entry.ts

* Allow only object, array, or null as _Object_ field base type (matching the API)
* Use JSON type definition from type fest

fix: correct Object type

---

lib/create-contentful-api.ts
lib/make-client.ts
lib/utils/client-helpers.ts
test/types/client/createClient.test-d.ts
test/types/client/getAssets.test-d.ts
test/types/client/getEntries.test-d.ts
test/types/client/parseEntries.test-d.ts

Replace existing client types (`ClientWith…`) with one generic client type (`Client<ChainModifiers>`). With this change the client and entry types follow the same format which should make it easier to read and understand.

chore: introduce generic client type

---

lib/create-contentful-api.ts
lib/types/query/query.ts
lib/types/query/select.ts
test/types/queries/asset-queries.test-d.ts
test/types/queries/entry-queries.test-d.ts
test/types/query-integer.test-d.ts
test/types/query-types/boolean.test-d.ts
test/types/query-types/date.test-d.ts
test/types/query-types/integer.test-d.ts
test/types/query-types/location.test-d.ts
test/types/query-types/number.test-d.ts
test/types/query-types/object.test-d.ts
test/types/query-types/richtext.test-d.ts
test/types/query-types/symbol.test-d.ts
test/types/query-types/text.test-d.ts
test/types/query.test-d.ts

Update select operator type to match the API.
* Split select filter into variations for assets and entries
* Require `content_type` when selecting for entry fields
* Remove `Partial` around `EntriesQueries` and `AssetQueries` because it makes required properties impossible
* Remove wildcard types from `EntriesQueries` and `AssetQueries` because it makes forbidden properties impossible
* Add simple `order` parameter type as stand in until we have a proper type for it
We want to guide users more when using queries. Currently it’s only possible to get some autocomplete support but the types don’t give hints as to what’s required for certain operators or which properties are not allowed. This PR lays the groundwork to add more helpful query types.

fix: limit select operator to allowed values

---

lib/types/query/location.ts

2 of my 3 TypeScript contexts don’t accept the location filter type without this change despite all 3 using the same TypeScript version.

fix: location filter type

---

lib/types/query/equality.ts
lib/types/query/query.ts
lib/types/query/search.ts
lib/types/query/util.ts
test/types/query.test-d.ts

Improve query types to better match API.
* add `links_to_asset` and `links_to_entry`
* enable equality, inequality, and full text search operators for symbol list fields

fix: improve query types for getEntries

---

lib/types/query/query.ts
lib/types/query/reference.ts
test/types/queries/entry-queries.test-d.ts
test/types/query.test-d.ts

Add [search on references](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references) to the query types. To not completely overload TypeScript with filters for nested entries, the specific paths are not checked in detail.

feat: add reference search to query types

---

lib/create-contentful-api.ts
lib/types/query/index.ts
lib/types/query/query.ts
lib/types/sys.ts
test/integration/getTags.test.ts
test/types/queries/tag-queries.test-d.ts
test/types/query-types/tagName.test-d.ts

One of the TODOS is to properly type the tagQuery filters, this PR addresses that.

fix: add proper type for TagQueries [DANTE-867]

---

README.md
TYPESCRIPT.md
lib/create-contentful-api.ts
lib/paged-sync.ts
lib/types/sync.ts
test/integration/sync.test.ts
test/integration/tests.test.ts
test/unit/mocks.ts
test/unit/paged-sync.test.ts

The `sync` method no longer uses global options, but now accepts client chains of `withoutLinkResolution` and `withoutUnresolvableLinks` to get different return shape from the API depending on `resolveLinks` and `removeUnresolved`, similar to `getEntry` and `getEntries`. Tests and documentation have been updated to reflect the changes.

chore: chain-specific behavior in sync [DANTE-870]

---

lib/create-contentful-api.ts
lib/types/query/query.ts

This PR addresses the second TODO about omit the locale from the list of fixed query options and only adding it where we don't have `WithAllLocales` chain modifier.

fix: remove the locale query filter from the list of FixedQueryOptions [DANTE-867]

---

test/integration/getEntry.test.ts
test/integration/tests.test.ts

fix: move getEntry tests from tests.test.ts to getEntry.test.ts [DANTE-867]

---

lib/types/query/query.ts
test/types/queries/asset-queries.test-d.ts
test/types/queries/entry-queries.test-d.ts

Add supported query parameters for `metadata.tags` to query types.

feat: add types for metadata.tags query parameters

---

lib/contentful.ts
lib/create-contentful-api.ts
lib/create-global-options.ts
lib/utils/validate-params.ts
test/unit/contentful.test.ts
test/unit/make-contentful-api-client.test.ts

Follow-up for https://github.com/contentful/contentful.js/pull/1783 to remove the old `resolveLinks` and `removeUnresolved` parameters on the JS level.
* Throw error when `resolveLinks` or `removeUnresolved` are used in query to alert JS users to new API.
* Throw error when `resolveLinks` or `removeUnresolved` are used in client creation to alert JS users to new API.
* Remove old parameters from global options.

chore: throw error when using old parameters

---

lib/types/query/order.ts
lib/types/query/query.ts
test/integration/getEntries.test.ts
test/types/queries/asset-queries.test-d.ts
test/types/queries/entry-queries.test-d.ts
test/types/queries/tag-queries.test-d.ts
test/types/query-types/boolean.test-d.ts
test/types/query-types/date.test-d.ts
test/types/query-types/integer.test-d.ts
test/types/query-types/location.test-d.ts
test/types/query-types/number.test-d.ts
test/types/query-types/object.test-d.ts
test/types/query-types/richtext.test-d.ts
test/types/query-types/symbol.test-d.ts
test/types/query-types/text.test-d.ts
test/types/query.test-d.ts

Add `order` parameter for `getAssets`, `getEntries`, and `getTags` queries.

feat: add order query parameter

---

lib/types/query/query.ts
lib/types/query/set.ts
lib/types/query/subset.ts
test/types/queries/entry-queries.test-d.ts
test/types/query-types/boolean.test-d.ts
test/types/query-types/date.test-d.ts
test/types/query-types/integer.test-d.ts
test/types/query-types/location.test-d.ts
test/types/query-types/number.test-d.ts
test/types/query-types/object.test-d.ts
test/types/query-types/richtext.test-d.ts
test/types/query-types/symbol.test-d.ts
test/types/query-types/text.test-d.ts

Add support for the `[all]` operator in `getEntries` query types.

feat: add all query parameter

---

lib/types/query/existence.ts
lib/types/query/order.ts
lib/types/query/query.ts
test/types/queries/asset-queries.test-d.ts

Some query parameters for `getAssets` where related to the asset file where still missing.
* Add operators for file properties and file size
* Add file URL and file size to `order` parameter values

chore: add more asset file query parameters

---

lib/create-contentful-api.ts
lib/utils/validate-search-parameters.ts
test/unit/utils/validate-search-parameters.test.ts

Disallow objects as query parameters at runtime. This check is in addition to type checks as object parameters are otherwise silently hidden leading to unexpected results and hard to find errors for users.

fix: disallow objects as query parameter values

---

TYPESCRIPT.md
lib/create-contentful-api.ts
lib/paged-sync.ts
lib/types/entry.ts
lib/types/query/existence.ts
lib/types/query/index.ts
lib/types/query/query.ts
lib/types/query/search.ts
lib/types/query/util.ts
lib/types/sync.ts
test/integration/getEntries.test.ts
test/integration/getEntry.test.ts
test/integration/parseEntries.test.ts
test/integration/sync.test.ts
test/types/client/getEntries.test-d.ts
test/types/client/parseEntries.test-d.ts
test/types/entry-d.ts
test/types/mocks.ts
test/types/queries/entry-queries.test-d.ts
test/types/query.test-d.ts
test/types/resolved-field.test-d.ts
test/unit/make-contentful-api-client-parseentries.test.ts
test/unit/make-contentful-api-client.test.ts
test/unit/mocks.ts

Introduce `EntrySkeletonType` type that replaces `FieldsType` in calls to `getEntry`, `getEntries`, and `parseEntries`. In addition to fields it contains the content type id and allows stronger typing of the returned values.

feat: add EntrySkeletonType combining fields with content type id [DANTE-946]

---

lib/types/query/order.ts
test/types/query-types/location.test-d.ts

Allow ordering entries by _Location_ fields.

fix: allow ordering entries by location

---

lib/types/query/existence.ts
lib/types/query/util.ts
test/types/query-types/boolean.test-d.ts
test/types/query-types/date.test-d.ts
test/types/query-types/integer.test-d.ts
test/types/query-types/location.test-d.ts
test/types/query-types/number.test-d.ts
test/types/query-types/object.test-d.ts
test/types/query-types/richtext.test-d.ts
test/types/query-types/symbol-array.test-d.ts
test/types/query-types/symbol.test-d.ts
test/types/query-types/text.test-d.ts

Add tests to make sure all query parameter types are compatible with strict modes and fix resulting errors.
* Fix existence filter
* Fix edge case with list of symbols field

fix: query parameters compatible with strict mode

---

DOCS.md
README.md
lib/contentful.ts
lib/create-contentful-api.ts
lib/index.ts
lib/make-client.ts
lib/types/client.ts
lib/types/index.ts
test/types/client/createClient.test-d.ts

Replace existing client types (`Client`, `ContentfulClientApi`, and `DefaultClient`) with just `ContentfulClientApi`, move it to the `types` folder, and link it in the docs.

chore: reduce number of client types

---

TYPESCRIPT.md

Unify Skeleton names in the examples of TYPESCRIPT.md

fix: unify Skeleton names in the examples [DANTE-953]

---

lib/create-contentful-api.ts
lib/types/asset.ts
lib/types/client.ts
lib/types/entry.ts
lib/types/index.ts
lib/types/query/index.ts
lib/types/query/query.ts
lib/types/sync.ts
lib/utils/client-helpers.ts
test/types/asset-d.ts
test/types/chain-options.test-d.ts
test/types/client/createClient.test-d.ts
test/types/queries/asset-queries.test-d.ts
test/types/queries/entry-queries.test-d.ts
test/types/query.test-d.ts

Document the client methods and reorganize the client type to create readable documentation.
* Put all client methods directly into `ContentfulClientApi` to generate readable documentation. Small caveats:
* `Locales` type parameter is now also available for methods that don’t need it.
* Client properties that can’t be used are now typed as `never` instead of omitted.
* Move `LocaleOption` into `…Queries` types to improve readability.
TypeDoc doesn’t do well with complex types. We can spend all day coming up with clever dynamic solutions for types but at least for those types that we want to cover with generated documentation we have to be a little bit more straightforward.

chore: document client methods

---

DOCS.md
lib/types/client.ts
lib/types/index.ts

Improve client method documentation and link methods from DOCS page. Overall this is an improvement of the current client documentation state but needs more work to finish.
* Change `ContentfulClientApi` to interface so it’s possible to link to its methods
* Link client methods from DOCS page
* Update client method examples to TypeScript
* Document more parameters (but some are still missing)
* Start marking types that users aren’t expected to interact with directly as `internal`

chore: improve client method documentation

---

.circleci/config.yml

re-add vault usage for the release step

chore: fix release step

---

.github/dependabot.yml

Axios new version is causing pipeline to fail on beta-v10, so we need to ignore this upgrade before the release of the v10

chore: ignore axios version upgrade by dependabot

---

DOCS.md
typedoc.json

fixing the contentful logo in typedoc

fix: using media to generate contentful logo correctly in typedoc output

---

lib/types/entry.ts
test/types/resolved-field.test-d.ts

Add support for the `in` validation in field types allowing users to narrow down number and text field values.
For example, take a content type field with the following validation.
```
{
"id": "textField",
"name": "text field",
"type": "Symbol",
"validations": [
{
"in": ['option 1', 'option 2']
}
],
…
}
```
We can translate this to the following types.
```typescript
type ExampleEntrySkeleton = EntrySkeletonType<{
textField: EntryFieldTypes.Symbol<'option 1' | 'option 2'>,
}>
type ExampleEntry = Entry<ExampleEntrySkeleton>
```
In contentful.js v9 this was already possible because we used native types to describe fields. Since we’re using abstract types in v10 we have to explicitly allow this.

feat: support in validation in entry field types

---

lib/types/asset.ts
lib/types/entry.ts
test/types/asset-d.ts
test/types/entry-d.ts
test/types/mocks.ts

Fix localization of asset types.
Fix two issues related to asset localization.
* Chain modifiers were not passed down when resolving asset links causing types to be generic (representing both the localized and unlocalized version).
* Asset localization was on the wrong level: on the asset instead instead of on each field.

fix: correct asset localization

---

package.json

Change entry points to point to production versions to get rid of debug logic and reduce bundle size.

fix: change entry points to prod versions

---

ADVANCED.md
lib/types/entry.ts
lib/types/link.ts

Introduce new `UnresolvedLink` type to better represent why there is a link where users expect a resolved entity.
contentful.js includes link objects in returned entries if linked entities could not be resolved. This is also represented in the types for linked entities which contain a union of an entity (for the resolved case) and a link (for the unresolved case). When users try to access the fields of a linked entry without checking whether the entity has been resolved it results in an error which doesn’t explain what happens. This PR introduces an explicit type for unresolved links which makes the error messages easier to understand by connecting the presence of the link in the type to the concept of link resolution.
Before:
After:

feat: add explicit unresolved link type

---

lib/types/content-type.ts

Adds types for `nodes` validation object in `FieldItem.validations`
* Changes enabledNodeTypes validation to only allow valid string values
* Adds validation type for the new embedded-resource-block node
This PR adresses both the addition of validations for the `embedded-resource-block` RichText node and also adds some missing RichText nodes to the validations object.
This PR is very similar to [the PR in contentful-management.js](https://github.com/contentful/contentful-management.js/pull/1858)

feat: add additional types for nodes validations

---

.gitignore
package-lock.json
package.json

Customers reported issues with javascript language features (optional chaining) on old browsers. 
By Downgrading the min supported browserslist config, we expect the build to polyfill unknown language features. 
The version is selected based on [this list](https://caniuse.com/?search=optional%20chaining).
Solves: #1901

fix: downgrade browseslist to support old browsers [PHX-2717]

---

lib/types/content-type.ts

Allow `null` value for validation `message`
It turns out the `message` value for validations can be set to `null`. This PR updates the Typescript type to reflect this.
The Typescript type is not correct for the possible value set for `message`

fix: allow null type for validation message

---

jest.config.js
lib/create-contentful-api.ts
package-lock.json
package.json

Major bump for `axios` and `contentful-sdk-core`

fix: bump axios 1.x [PHX-2740]

---

package-lock.json
package.json

- Bump contentful-resolve-response to remove regex named capture group

chore: bump contentful-resolve-response

---

lib/contentful.ts

add requestLogger and responseLogger options to CreateClientParams to match options listed in documentation and contentful-sdk-core
Closes #434

fix(typing): add requestLogger and responseLogger options

---

package-lock.json
package.json

upgrade to address https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
fixes #2046

fix(axios): csrf vulnerability

---

package.json

This will make sure the core, CDA and CMA libs all support the very same browsers and node versions.
Partner PRs:
* https://github.com/contentful/contentful-sdk-core/pull/437
* https://github.com/contentful/contentful-management.js/pull/2176

normalize babel syntax transforms with other public CTF libs

---

lib/create-contentful-api.ts
lib/utils/normalize-select.ts
lib/utils/query-selection-set.ts
test/integration/getAssets.test.ts
test/integration/getEntries.test.ts

Ensure that `sys` is selected when `withContentSourceMaps` option is enabled but `sys` isn't present in `query.select`

feat: ensure entity.sys is selected when withContentSourceMaps is enabled

---

lib/contentful.ts
lib/create-contentful-api.ts
lib/utils/validate-params.ts
package-lock.json
package.json
test/integration/getAsset.test.ts
test/integration/getAssets.test.ts
test/integration/getEntries.test.ts
test/integration/getEntry.test.ts
test/integration/utils.ts
test/unit/contentful.test.ts
test/unit/utils/validate-params.test.ts

This should make it easier for customers to set up Content Source Maps. Once this is merged, enabling the CSM alpha feature will encode the CPA response directly reducing the steps needed to set this up
We have added a wrapper function the conditionally encodes the CPA response depending on whether the alpha feature is enabled or not
-   [x] rename the alpha feature from `withContentSourceMaps` to `includeContentSourceMaps`
-   [x] it should encode the CPA response directly (encodeCPAResponse)
-   [x] it loads the content source maps in the background
-   [x] Import it from the content-source-maps package (smaller bundlesize than live preview SDK)
NOTE:
We haven't added tests for the entry endpoint because the test entry in the space uses unsupported fields & we have realised that we …

feat: encode CPA response when csm alpha feature is enabled [TOL-2080]

---

package-lock.json
package.json

addresses https://github.com/contentful/contentful.js/issues/2246
The bug in our SDK can be traced to the upgrade of `axios` from 1.6.8 to 1.7.x ([here](https://github.com/contentful/contentful.js/compare/v10.11.0...v10.11.1)). I'm not yet certain if this new version of `axios` has a bug, of if a fix there exposed a bug in our implementation of it. For now we'll pin our `axios` dependency to the last known compatible minor version, 1.6.x

fix: pin axios to 1.6.x to prevent request params from being duplicated on retries

---

.github/dependabot.yml
package-lock.json
package.json

[Dependabot forced an update](https://github.com/contentful/contentful.js/pull/2255) to a known incompatible minor version (1.7.x) of axios after we had attempted to pin it at the latest known compatible version (1.6.x). This reverts that change, and also updates the dependabot config to prevent this from happening again.

fix: pin axios to 1.6.x and prevent dependabot from overwriting the package manifest

---

lib/types/query/reference.ts

According the docs the queries on references are allowed. While it works for single references, it leads to a ts error on arrays. As it appears to be a typing problem on CDK's side.
https://github.com/contentful/contentful.js/blob/master/TYPESCRIPT.md#limitation
Add an array of entries to `ReferenceSearchFilters` type to enable the same behavior for array of entries as for single entries.
Example of the wrong behavior:
```typescript
const entries = client.getEntries<
EntrySkeletonType<
{
tags?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<EntrySkeletonType>>;
},
'example'
>
>({
content_type: 'example',
'fields.tags.sys.id[in]': ['foo', 'bar'] // TS Error: Object literal may only specify known properties, and ''fields.tags.sys.id[in]'' does not exist in type …
```

fix: typescript for queries on array references

---

lib/types/entry.ts
lib/types/resource-link.ts
package-lock.json
package.json
test/integration/parseEntries.test.ts
test/types/mocks.ts
test/types/resolved-field.test-d.ts

Add support for external references. 
Since these aren’t resolved they skip the `withoutUnresolvedLinks` behavior and are always kept.
I’ve only updated the `parseEntries` part of the integration tests because it’s enough to cover the simple logic we currently have. The underlying behavior is the same for `getEntries` anyway. If we complicate the logic in the future we can expand the tests as well.

feat: add support for external references

---

lib/types/asset.ts
lib/types/link.ts
lib/types/metadata.ts
lib/types/query/query.ts
lib/types/query/select.ts
test/types/queries/asset-queries.test-d.ts
test/types/queries/entry-queries.test-d.ts

Add [Taxonomy concept](https://www.contentful.com/help/taxonomies-overview/) links to entries (This feature i currently in beta).
To allow beta customers to use the newly exposed `concepts` field on `metadata`, we add it as an optional field.
For now, taxonomy concepts are exclusive to Entry. The change introduces the smallest possible footprint to introduce this variation for Entry metadata. It should also allow for easy adoption of the feature on assets at a later point in time.

feat(taxonomy): add concepts to entry metadata [GROOT-1440]

---

lib/contentful.ts
lib/create-contentful-api.ts
lib/utils/validate-params.ts
package-lock.json
package.json
test/integration/getAsset.test.ts
test/integration/getAssets.test.ts
test/integration/getEntries.test.ts
test/integration/getEntry.test.ts
test/integration/utils.ts
test/unit/contentful.test.ts
test/unit/utils/validate-params.test.ts

Remove alpha for Content Source Maps. Instead we have a direct option now on the Client initialization parameters.
Also marks the alpha features one as deprecated:

feat: remove alpha for content source maps [TOL-2045]

---

package.json

Due to a accidentally published v11 version,
we are not able to completely verify what semantic release will do when we publish another `BREAKING CHANGE` commit.
This PR seeks to do two things:
- Critically, add `--dry-run` flag https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun to semantic release to prevent an actual publish.
- Create a merge commit on master, which given the CI vault token is the only way to publish commits, is our only way to truly test this.
If this works (and outputs 11.0.2 as the _potential_ new version) we'll go ahead and remove that flag in the contentful v11 feature branch and merge+deploy it knowing that it will do what we want.
If this doesn't work, we'll remove that dry-run flag in another PR and see what we can do to correct the …

BREAKING CHANGE: adding dry run flag, BC commit tag to force major

---

rollup.config.js

Import assertions are already deprecated. Failing to fix this will cause everyone on Node.js 22 (LTS this month!) unable to push their changes, as build is a part of prepush hook.

Replace import assertion with import attribute

---

lib/create-contentful-api.ts
lib/types/asset.ts
lib/types/client.ts
lib/types/collection.ts
lib/types/content-type.ts
lib/types/entry.ts
lib/types/link.ts
lib/types/locale.ts
lib/types/metadata.ts
lib/types/query/equality.ts
lib/types/query/existence.ts
lib/types/query/location.ts
lib/types/query/order.ts
lib/types/query/query.ts
lib/types/query/range.ts
lib/types/query/reference.ts
lib/types/query/search.ts
lib/types/query/select.ts
lib/types/query/set.ts
lib/types/query/subset.ts
lib/types/query/util.ts
lib/types/space.ts
lib/types/sync.ts
lib/types/sys.ts
lib/types/tag.ts
lib/utils/client-helpers.ts
lib/utils/normalize-select.ts

Fix types not working in ESM mode

---

MIGRATION.md

Added my webpack hints from https://github.com/contentful/contentful.js/issues/2318#issuecomment-2393549369 to the mirgation readme

add hint about webpack to MIGRATION.md

---

lib/types/entry.ts
test/types/client/getEntries.test-d.ts

Gives includes Entry and Asset arrays at least basic skeleton types.
From there they can then conveniently be narrowed down to the desired types.
Currently the types are `any`, which is difficult to work with.
Casting from the outside is awkward too especially since we have the modifiers that should propagate.
So we should just set the correct types from the start.
I need to do some processing on the includes and don't want to cast them all the time.

feat: give includes basic entry and asset types instead of any

---

lib/types/sys.ts
test/types/mocks.ts
test/unit/mocks.ts

Adds the `publishedVersion` field to the `EntitySys` type.
Closes #2408 
We'd like to reference the published version of a given entry, but the current typing does not include this field despite it existing on the data returned from the `getEntries` call (and also mentioned in the [docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes)).
The doc also mentions the `publishedVersion` field applies to content types, but I did not see that field returned in my testing so I did not add it to the `ContentTypeSys` type.

feat: add publishedVersion to EntitySys

---

lib/types/concept-scheme.ts
lib/types/concept.ts

- Fixes the typing for `Link` objects from the taxonomy API. They are returned as "UnresolvedLinks" (where the parent key is `sys`)
- Change `Link` type to `UnresolvedLink` in `types/concept.ts` and `types/concept-schemes.ts`
- Incorrect typing would lead to incorrect handling of the response objects.
- N/A
- N/A

fix: incorrect typing for unresolved links for taxonomy []

---

package-lock.json
package.json

Explicitly upgrades axios to latest 1.7.9 to ensure installers get the latest version without needing to regen their package-lock.json files or run `npm audit fix`

fix: explicitly upgrade axios to 1.7.9 [ZEND-5815]

---

lib/types/query/query.ts
test/integration/getConcepts.test.ts

In the original PR for the taxonomy CDA beta, the concept scheme query parameter for the concept list query was not in the correct format. This PR remedies that issue.
We should also follow up to validate the test scenario - due to the test data set up in the test org, the test that was supposed to catch an issue like this was passing, since the correct param and an incorrect param returned the same data. (reasoning being that there are only two concepts in the whole org, after this PR I will add another concept which should make the test more valid).
Important note: Taxonomy in the CDA is still a beta feature, so there is no worry on this being a breaking change

fix: [GROOT-1744] fix concept scheme parameter on concept list query

---

package-lock.json
package.json

`15 vulnerabilities (1 low, 11 moderate, 3 high)` -> `7 vulnerabilities (1 low, 5 moderate, 1 high)`
Fix critical security vulnerabilities:
1. `form-data`, which is a dependency of axios: 
- raised by https://contentful.atlassian.net/browse/ZEND-6686
- [fixed in axios package](https://github.com/axios/axios/issues/6969)
- https://security.snyk.io/vuln/SNYK-JS-FORMDATA-10841150
2. @eslint/plugin-kit  <0.3.3
3. @octokit/endpoint
```
contentful.js git:(master) 🌺 npm audit
@babel/helpers  <7.26.10
Severity: moderate
Babel has inefficient RegExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/helpers
@babel/runtime  <7.26.10
Severity: moderate
Babel has …
```

chore(dependencies): fix critical axios and other security vulnerabilities[DX-291]

---

package-lock.json
package.json

Update vitest from v2 -> v3, to placate [dependabot build/security issue](https://github.com/contentful/contentful.js/security/dependabot/101)
[migration guide](https://vitest.dev/guide/migration.html)
I used vs-code/agent mode and claude to analyze our codebase to ensure this migration would not break our build/tests:

chore(dependency): update vitest to placate dependabot [DX-291]

---

.gitignore
.npmrc
package-lock.json
package.json

Addresses two issues:
- Explicitly bump axios version to stable version to address security vulnerabilities
- Add a shared `.npmrc` config to add npm as the registry for `@contentful` scoped packages
The `package-lock.json` file was already updated to `12.2.2` for axios, this now explicitly sets it in the `package.json` file. Also adding the `.npmrc` to ensure that packages are installed from the correct registry. 
Addresses: #2567

fix: bump axios and add shared .npmrc config [DX-422]
